networks:
  pihole_lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.8.0/24
          gateway: 192.168.8.1
          ip_range: 192.168.8.14/32

  dns_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    networks:
      pihole_lan:
        ipv4_address: 192.168.8.14
      dns_internal:
        ipv4_address: 172.20.0.2
    environment:
      TZ: "Europe/Berlin"
      FTLCONF_webserver_api_password: "correct horse battery staple"
      FTLCONF_dns_listeningMode: "ALL"
      FTLCONF_dns_upstreams: "172.20.0.3#5335"
      ServerIP: "192.168.8.14"
    volumes:
      - ./pihole_etc:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    depends_on:
     - unbound
    restart: unless-stopped
    

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound
    depends_on:
      - redis
    networks:
      dns_internal:
        ipv4_address: 172.20.0.3
    volumes:
      # klutchell/unbound reads custom *.conf files from this directory
      - ./unbound/custom.conf.d:/etc/unbound/custom.conf.d:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: unbound-redis
    networks:
      dns_internal:
        ipv4_address: 172.20.0.4
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis-data:
