networks:
  dns_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  local_bridge:
    driver: bridge

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    networks:
      local_bridge:
      dns_internal:
        ipv4_address: 172.20.0.2
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
    environment:
      TZ: "Europe/Berlin"
      FTLCONF_webserver_api_password: ${WEB_PASSWORD}
      FTLCONF_dns_listeningMode: "ALL"
      FTLCONF_dns_upstreams: "unbound#5335"

    volumes:
      - ./pihole:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    
    # based on https://docs.pi-hole.net/docker/#note-on-capabilities
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
      - CAP_NET_ADMIN
      - CAP_SYS_NICE
      - CAP_CHOWN
      - CAP_SYS_TIME
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- NET_ADMIN 
    depends_on:
      - unbound
    restart: unless-stopped

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound
    depends_on:
      - redis
    networks:
      dns_internal:
        ipv4_address: 172.20.0.3
    ports:
      - 5335:5335 # based on `unbound/custom.conf.d/00-listen.conf`
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      # klutchell/unbound reads custom *.conf files from this directory
      - ./unbound/custom.conf.d:/etc/unbound/custom.conf.d:ro
      - ./unbound/logs:/var/log/unbound
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: unbound-redis
    networks:
      dns_internal:
        ipv4_address: 172.20.0.4
    ports:
      - 6379:6379 # based on `unbound/custom.conf.d/cachedb.conf`
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis-data:
